name: lifestyle
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bezier_chart: ^1.0.17+1
  canonical_url: ^1.0.4
  carousel_slider: ^1.3.0
  clay_containers: ^0.2.3
  cloud_firestore: ^0.14.3+1
  connectivity: ^3.0.2
  country_code_picker: ^1.7.0
  cupertino_icons: ^1.0.0
  custom_tab: ^0.0.5
  date_time_picker: ^1.1.0
  datetime_picker_formfield: ^1.0.0
  feather_icons_flutter: ^4.7.4
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.3
  firebase_database: ^4.4.0
  firebase_storage: ^5.2.0
  flare_flutter: ^2.0.6
  fluid_bottom_nav_bar: ^1.2.0
  flutter_colorpicker: ^0.3.5
  flutter_inappwebview: ^4.0.0+4
  flutter_local_notifications: ^4.0.1+1
  flutter_phone_direct_caller: ^1.0.1
  flutter_rounded_progress_bar: ^0.2.0
  flutter_slidable: ^0.5.7
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.18.0
  fluttertoast: ^7.1.8
  font_awesome_flutter: ^8.12.0
  get_it: ^6.0.0
  getwidget: ^1.2.4
  google_fonts: ^1.1.0
  horizontal_picker: ^1.0.0
  http: ^0.12.0
  image_picker: ^0.6.0
  image_picker_widget: ^1.0.2
  intl: ^0.16.1
  json_annotation: any
  launch_review: ^3.0.1
  location: ^3.0.2
  logger: any
  login_fresh: ^1.0.8
  material_design_icons_flutter: ^3.0.39
  mime: ^0.9.6+2
  modal_progress_hud: ^0.1.3
  outline_material_icons: ^0.1.1
  path: ^1.7.0
  path_provider: ^2.0.1
  percent_indicator: ^2.1.9+1
  permission_handler: ^5.1.0+2
  progress_dialog: ^1.2.0
  progress_hud: ^1.1.0
  provider: ^5.0.0
  retrofit: any
  rxdart: ^0.26.0
  screenshot: ^0.3.0
  searchable_dropdown: ^1.1.3
  share: ^0.6.5+4
  shared_preferences: ^2.0.3
  table_calendar: ^2.3.3
  timeago: ^2.0.8
  toast: ^0.1.5
  url_launcher: ^5.7.10
  webview_flutter: ^2.0.2
  youtube_player_iframe: ^1.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "launcher_icon"
  ios: false

flutter:

  uses-material-design: true
  assets:
    - assets/plane_bg.jpg
    # - img/offline.jpg
    - assets/plane.jpg
    - assets/loading_bg.jpg
    - assets/splash_bg.jpg
    - assets/logo2.png
    - assets/list.png
    - assets/sound/
    - images/logo_icon.png
    - images/logoOS.png
    - images/ic_default_image.png
    - images/ic_side_settings.png
    - images/ic_hamburger_menu.png
    - images/ic_dietplan.jpg
    - images/ic_cleaneatings.jpg
    - images/ic_foodforstrength.jpg
    - images/ic_vegan.jpg
    - images/ic_flexitarian.jpg
    - images/ic_atkins.jpg
    - images/ic_ketogenic.jpg
    - images/ic_paleo.jpg
    - images/ic_step.png
    - images/ic_pulse.png
    - images/ic_avocados.jpg
    - images/ic_beans.jpg
    - images/ic_cheese.jpg
    - images/ic_eggs.jpg
    - images/ic_fish.jpg
    - images/ic_fruits.jpg
    - images/ic_greekyoghurt.jpg
    - images/ic_leanmeat.jpg
    - images/ic_legumes.jpg
    - images/ic_meat.jpg
    - images/ic_shrimps.jpg
    - images/ic_vegetables.jpg
    - images/ic_wholegrains.jpg
    - assets/travel_image/
    - assets/shopping_image/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf
    - family: Geometria
      fonts:
        - asset: fonts/Geometria-Bold.ttf
        - asset: fonts/Geometria-ExtraBold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-Black.ttf
